### ISSUE TITLE
Impute capital gains

### ISSUE THREAD

**Issue by MaxGhenis** [nikhilwoodruff/frs#12]
Moving discussion from https://github.com/PSLmodels/openfisca-uk/issues/40 which covers implementation of the logic.

Neither FRS nor SPI microdata includes capital gains, but we could impute them from [HMRC statistical tables](https://www.gov.uk/government/statistics/capital-gains-tax-statistical-tables). Here are some high level stats from 2018-19:
* 256,000 individuals paid 8.8bn tax on 59.3bn capital gains (table 1)
* More than half of gains are from people aged 55 or older (table 6)
* Table 3 has the most important information (far left column is lower limit, left of each pair of columns is individuals in 000s, right is gains in millions):
![image](https://user-images.githubusercontent.com/6076111/112093468-aebcf700-8b56-11eb-8575-df048bea063f.png)

The [Office of Tax Simplification](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/935073/Capital_Gains_Tax_stage_1_report_-_Nov_2020_-_web_copy.pdf) has some additional data. For example, the below chart shows that people bunch capital gains below the 12,300 threshold; while the report includes data for some charts, it omits it from this one.
![image](https://user-images.githubusercontent.com/6076111/112093980-9ef1e280-8b57-11eb-9196-d5786a4f94da.png)

**Comment by MaxGhenis** [comment]
@jpycroft, Rick suggested checking in with you on this discussion. Do you know of UK capital gains microdata we could impute, or other summary statistics that could be useful?

**Comment by jpycroft** [comment]
Hi Max,
I've just double-checked in my European Commission files, but there isn't anything for the UK. 
The cross-country work on wealth is done using HCFS data from the European Central Bank, and so is only for Euro Area countries. For the Italian and German OG models, we also use national data from Banca d´Italia and the German SOEP survey. 
(You may be aware) there is a UK Wealth and Assets Survey, though I haven't looked into the data: https://www.ons.gov.uk/peoplepopulationandcommunity/personalandhouseholdfinances/debt/methodologies/wealthandassetssurveyqmi
Cheers, 
Jon

@MaxGhenis @nikhilwoodruff

**Comment by nikhilwoodruff** [comment]
Thanks @jpycroft - looks like the UK Wealth and Assets Survey is probably usable to us on the UK Data Service. @MaxGhenis we probably need to think about adjusting for the time periods - if we're (soon to be) using the FRS 2019-20, and would like to adjust for high incomes using the SPI 2016-17, and the Wealth and Assets Survey 2016-18, we might need some kind of planning to do this accurately?

**Comment by MaxGhenis** [comment]
Ah so the Wealth and Assets Survey includes capital gains?

**Comment by MaxGhenis** [comment]
The [codebook](https://docs.google.com/spreadsheets/d/1Jg3pAkunu8g1xc04taDM3fBYPhsLXw-6Zswga-Aw3tA) for the second-most-recent Wealth and Assets Survey does not show capital gains.

**Comment by MaxGhenis** [comment]
Moving discussion back to https://github.com/PSLmodels/openfisca-uk/issues/101
